### ISSUE TITLE
Buttons don't work on Gnome 3.26

### ISSUE THREAD

**Issue by ainola** [laserb/gnome-shell-extension-suspend-button#27]
Ever since I updated to Gnome 3.26, neither the suspend button nor the power button work.

**Comment by Hasbreak** [comment]
I can confirm that the bug also affects me on Arch.

**Comment by craigjackson** [comment]
```
JS ERROR: TypeError: this.systemMenu._onSuspendClicked is not a function
                                          Extension<._onSuspendClicked@/home/xxxxxxxx/.local/share/gnome-shell/extensions/suspend-button@laserb/extension.js:192:9
                                          wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
```

**Comment by jackpot51** [comment]
Fixes here, if you are interested: https://github.com/system76/gnome-shell-extension-suspend-button

**Comment by asbachb** [comment]
What's about a Pull Request? Or do you plan to publish it on gnome extensions?

**Comment by jackpot51** [comment]
It was merged into this repository, so I would assume it would be available soon.

**Comment by laserb** [comment]
The pull request is here: #24 . An updated version is under review and should be available soon.

**Comment by JanezStupar** [comment]
@laserb 'sup?

**Comment by laserb** [comment]
It is available now.

**Comment by genodeftest** [comment]
This extension update has been unpushed from extensions.gnome.org, right? I'm asking because I updated to the latest version and those buttons still don't work.

**Comment by laserb** [comment]
Yes, it seemed to cause more problems than it solved. An updated version is on the way. But the reviewing process to get it on the extension site takes some time.

**Comment by laserb** [comment]
New version is now available via extensions.gnome.org

**Comment by ainola** [comment]
Thank you for your hard work, Sir.

**Comment by scr4bble** [comment]
Hi,
this still doesn't work for me. Any ideas ?

`JS ERROR: TypeError: this.systemMenu._onSuspendClicked is not a function
                                            Extension<._onSuspendClicked@/home/xxxxx/.local/share/gnome-shell/extensions/suspend-button@laserb/extension.js:192:9
                                            wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22`

`$ gnome-shell --version
GNOME Shell 3.26.2
`
The extension is up to date.
